### ISSUE TITLE
Xtensive.Orm.Web rollback transation on exception

### ISSUE THREAD

**Issue by mdissel** [DataObjects-NET/dataobjects-net#140]
By default the outermost transaction will be rolled back when an exception has occured, but how can we handle the situation that we need to update the action to a failed status or does this mean we have to capture all exceptions and never let them flow to the UI (through some other middleware)?

(or for example some logging/event store handler that's being handled by DO)

Thanks

**Comment by alex-kulakov** [comment]
Hello mdissel,

As I understand you have some informative exceptions for UI and they trigger SessionManager so it rollbacks outermost transaction, right?

**Comment by mdissel** [comment]
Correct! 
Sample:
- New HttpRequest
- Create log entries using the current session
- ValidationException is raised
- Log entries should still be added to the database
So some database actions should not be rolled back..

**Comment by alex-kulakov** [comment]
In that case our session manager is very inconvenient for you, I agree. I guess we should provide more control or even rethink the extension completely. I see several drawbacks in it.

By the way, tell me the version you use.

**Comment by mdissel** [comment]
Thanks! just make the changes on top of the latest version.

**Comment by alex-kulakov** [comment]
@mdissel , I've been experimenting with ```SessionManager``` alternatives for a while.

I really thing of giving user an instance of ```Session``` itself and ```TransactionScope``` if required instead of SessionManager. Having something static is a bad idea as well as session activations - they just mess around with you and not so many people really understand how to work with them properly.Would it be convenient for you to have session/transaction scope provided as parameter of some action? My experimental idea of how it may work is like so:

```
public class HomeController : Controller
{
  // Here, both session and transaction are opened but only the session instance is provided
  // I assume infrastructure should complete the transaction scope in such cases.
  public IActionResult Index(Session session)
  {
     var result = session.Query.All<SomeEntity>().FirstOrDefault();
     // some other work
  }

  // Here, both session and transaction instances are opened and provided.
  // you can decide whether complete the transaction scope or not, Infrastructure just disposes
  // both instances.
  public IActionResult Security(Session session, TransactionScope transactionScope)
  {
     var result = session.Query.All<SomeEntity>().FirstOrDefault();
     if (result== null) {
       _ = new SomeEntity();
    }
    // some other work
    transactionScope.Complete();
  }

  // obviously action does not need session
  // so session opening should be omitted
  public IActionResult About()
  {
     ...
  }
}
```

Such approach was some downside - it not possible to pass a ```Session``` instance to controller's constructor(s). Probably there are some cases when it may be required, but I have couple ideas how to do this.

By the way, if you need session and transaction opened in all of your actions you may specify them as scoped services.
```
    public void ConfigureServices(IServiceCollection services)
    {
      var domain = Domain.Build();
      services.AddSingleton<Domain>(domain);
      services.AddScoped<Session>((serviceProvider) => {
        var d = serviceProvider.GetRequiredService<Domain>();
        return d.OpenSession();
      });

      services.AddScoped<TransactionScope>((serviceProvider) =>
      {
        var s = serviceProvider.GetRequiredService<Session>();
        return s.OpenTransaction();
      });

      services.AddControllersWithViews();
    }
```

After that you can get them in actions like 

```
   public IActionResult Index([FromServices] Session session, [FromServices] TransactionScope transactionScope)
   {
     return View();
   }
```

No extra extension required and full control of when to complete transaction scope. It is probably suitable for rare cases but still.

**Comment by alex-kulakov** [comment]
This is not a final version though, It probably will change but I really want to keep this approach of direct access to session instance somehow. It depends on what is allowed by the Asp.Net Core, maybe I will have to create some sort of wrapper for Session and TransactionScope instances.
