### ISSUE TITLE
Can PostgreSQL support 15?

### ISSUE THREAD

**Issue by 1340896123** [DataObjects-NET/dataobjects-net#325]

**Comment by alex-kulakov** [comment]
Hello,

Starting from 7.0, DataObjects.Net is capable of working with PostgreSQL 15, thought it is not declared in supported list (because our test infrastructure for this version don't include PostgreSQL 15 as test storage). Since there are no breaking changes of feature set we use, it works just fine. If won't be any changes in system views structure or SQL statements then DataObjects.Net will work. If you already work with PostgreSQL it worth trying to install v15 in parallel with current instance and give it a try

**Comment by alex-kulakov** [comment]
I tested it, now it's for sure, added to supported databases list
